[package]
name = "unofficial-codex-utils-template"
description = "Unofficial downstream package of the OpenAI Codex Rust workspace (codex-utils-template)."
repository = "https://github.com/f4ah6o/unofficial-codex-rs"
publish = true
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dev-dependencies]
pretty_assertions = { workspace = true }

[lib]
name = "codex_utils_template"
doctest = false
