
[package]
edition.workspace = true
license.workspace = true
name = "unofficial-codex-cloud-tasks-mock-client"
description = "Unofficial downstream package of the OpenAI Codex Rust workspace (codex-cloud-tasks-mock-client)."
repository = "https://github.com/f4ah6o/unofficial-codex-rs"
publish = true
version.workspace = true

[lib]
name = "codex_cloud_tasks_mock_client"
path = "src/lib.rs"
test = false
doctest = false

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
codex-cloud-tasks-client = { workspace = true }
diffy = { workspace = true }
