[package]
name = "unofficial-codex-utils-oss"
description = "Unofficial downstream package of the OpenAI Codex Rust workspace (codex-utils-oss)."
repository = "https://github.com/f4ah6o/unofficial-codex-rs"
publish = true
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
codex-core = { workspace = true }
codex-lmstudio = { workspace = true }
codex-model-provider-info = { workspace = true }
codex-ollama = { workspace = true }

[lib]
doctest = false
